name: BirthdayBot_Automation

on:
  schedule:
    # Запуск каждый день в 06:00 по UTC (что равно 09:00 по МСК)
    - cron: '0 6 * * *'
  workflow_dispatch: # Позволяет запустить вручную через вкладку Actions

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Копирование кода из репозитория
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка библиотек
        run: |
          pip install pandas openpyxl python-telegram-bot pytz requests

      - name: Запуск скрипта поздравлений
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          THREAD_ID: ${{ secrets.THREAD_ID }}
        run: python bot.py
